<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yolol</string>
	</array>
	<key>foldingStartMarker</key>
	<string>[\(]</string>
	<key>foldingStopMarker</key>
	<string>[\)]</string>
	<key>name</key>
	<string>Yolol</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.yolol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number_sign.yolol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.......................................................................</string>
			<key>name</key>
			<string>invalid.length.yolol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.yolol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.yolol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.yolol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.yolol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(not|abs|sqrt|sin|cos|tan|asin|acos|atan)</string>
			<key>name</key>
			<string>support.function.yolol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(if|then|else|end|goto)</string>
			<key>name</key>
			<string>keyword.control.yolol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\B\-)?\b[0-9]+|:)</string>
			<key>name</key>
			<string>constant.numeric.yolol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\+\-*/%=]</string>
			<key>name</key>
			<string>keyword.operator.arithmtic.yolol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|>=|&lt;=|[>&lt;])</string>
			<key>name</key>
			<string>keyword.operator.comparison.yolol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yolol</string>
</dict>
</plist>